# Generated by Django 5.2.3 on 2025-06-17 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cespite', models.CharField(max_length=255, unique=True, verbose_name='Cespite / N° Patrimônio')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modello', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('stato', models.CharField(default='Disponibile', max_length=50)),
                ('data_acquisto', models.DateField(blank=True, null=True)),
                ('data_sostituzione_prevista', models.DateField(blank=True, null=True)),
                ('password_administrator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password Admin')),
                ('locazione_magazzino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Locazione in Magazzino')),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('dipartimento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contratto', models.CharField(blank=True, max_length=50, null=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assegnazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assegnazione', models.DateField()),
                ('data_restituzione', models.DateField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.dispositivo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Preparazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_richiesta', models.CharField(choices=[('Nuova Assunzione', 'Nuova Assunzione'), ('Sostituzione', 'Sostituzione')], max_length=50)),
                ('stato_preparazione', models.CharField(choices=[('In attesa specifiche', 'In attesa specifiche'), ('Pronto per preparazione', 'Pronto per preparazione'), ('Completato', 'Completato')], default='In attesa specifiche', max_length=50)),
                ('nome_nuovo_utente', models.CharField(blank=True, max_length=100, null=True)),
                ('cognome_nuovo_utente', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
                ('dipartimento_nuovo_utente', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo_vecchio_manuale', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_sostituzione', models.TextField(blank=True, null=True)),
                ('ticket_helpdesk', models.CharField(blank=True, max_length=100, null=True)),
                ('tipologia_pc_richiesta', models.CharField(blank=True, max_length=50, null=True)),
                ('note_software', models.TextField(blank=True, null=True)),
                ('data_pianificazione', models.DateField(blank=True, null=True)),
                ('mail_inviata', models.BooleanField(default=False)),
                ('dati_in_scsm', models.BooleanField(default=False)),
                ('in_ars', models.BooleanField(default=False)),
                ('delivery_inviato', models.BooleanField(default=False)),
                ('assegnazione', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.assegnazione')),
                ('dispositivo_vecchio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sostituzioni', to='gestao.dispositivo')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.utente')),
            ],
        ),
    ]
