# Generated by Django 5.2.3 on 2025-06-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparazione',
            name='dispositivo_vecchio_manuale',
        ),
        migrations.AddField(
            model_name='preparazione',
            name='dispositivo_nuovo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assegnazioni_come_nuovo', to='gestao.dispositivo', verbose_name='Nuovo Dispositivo dal Magazzino'),
        ),
        migrations.AlterField(
            model_name='preparazione',
            name='dispositivo_vecchio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sostituzioni_come_vecchio', to='gestao.dispositivo'),
        ),
    ]
