# Generated by Django 5.2.3 on 2025-06-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_remove_preparazione_dispositivo_vecchio_manuale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparazione',
            name='tipologia_pc_richiesta',
            field=models.CharField(blank=True, choices=[('Office', 'Office'), ('CAD', 'CAD')], max_length=50, null=True),
        ),
    ]
