# Generated by Django 5.2.3 on 2025-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_preparazione_tipologia_pc_richiesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparazione',
            name='categoria',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Stagista', 'Stagista/Interinale'), ('Priorità', 'Priorità'), ('Riassegnazione', 'Riassegnazione/Extra')], default='Standard', max_length=50, verbose_name='Categoria'),
        ),
    ]
