# Generated by Django 5.2.3 on 2025-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_preparazione_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparazione',
            name='categoria',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Stagista', 'Stagista'), ('Interinale', 'Interinale'), ('Priorità', 'Priorità'), ('Riassegnazione', 'Riassegnazione'), ('Extra', 'Extra')], default='Standard', max_length=50, verbose_name='Categoria'),
        ),
    ]
