# Generated by Django 5.2.3 on 2025-06-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_preparazione_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='cespite',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Cespite / N° Patrimônio'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='stato',
            field=models.CharField(choices=[('Disponibile', 'Disponibile'), ('Assegnato', 'Assegnato'), ('In Bonifica', 'In Bonifica'), ('Rottamato', 'Rottamato')], default='Disponibile', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('Office', 'Office'), ('CAD', 'CAD'), ('Notebook', 'Notebook generico'), ('PC Fisso', 'PC Fisso generico'), ('iMac', 'iMac'), ('Wacom', 'Wacom'), ('Altro', 'Altro')], max_length=50),
        ),
    ]
