# Generated by Django 5.2.3 on 2025-06-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_dispositivo_cespite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dipartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('Office', 'Office'), ('CAD', 'CAD'), ('Notebook', 'Notebook generico'), ('PC Fisso', 'PC Fisso generico'), ('Wacom', 'Wacom'), ('Altro', 'Altro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='utente',
            name='dipartimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.dipartimento'),
        ),
    ]
