# Generated by Django 5.2.3 on 2025-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_preparazione_tecnico_responsabile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparazione',
            name='data_pianificazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Ora Pianificata'),
        ),
    ]
