# Generated by Django 5.2.3 on 2025-06-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_sede_preparazione_luogo_intervento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='stato',
            field=models.CharField(choices=[('Disponibile', 'Disponibile'), ('Riservato', 'Riservato'), ('Assegnato', 'Assegnato'), ('In Bonifica', 'In Bonifica'), ('Rottamato', 'Rottamato')], default='Disponibile', max_length=50),
        ),
    ]
