# Generated by Django 5.2.3 on 2025-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_dispositivo_stato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utente',
            options={'ordering': ['cognome', 'nome']},
        ),
        migrations.AlterField(
            model_name='utente',
            name='tipo_contratto',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Esterno', 'Esterno'), ('Stagista', 'Stagista'), ('Interinale', 'Interinale')], default='Interno', max_length=50),
        ),
    ]
