# Generated by Django 5.2.3 on 2025-06-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_alter_utente_options_alter_utente_tipo_contratto'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparazione',
            name='tipo_contratto_nuovo_utente',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Esterno', 'Esterno'), ('Stagista', 'Stagista'), ('Interinale', 'Interinale')], default='Interno', max_length=50, verbose_name='Tipo Contratto (Nuovo Utente)'),
        ),
    ]
